In [4]:
#Problem 1
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_arr = np.empty((2, 2))
print("1. Empty array:\n", empty_arr)

# 2. Initialize an all-one array with size 4x2
ones_arr = np.ones((4, 2) ,dtype=int)
print("\n2. All-one array:\n", ones_arr)

# 3. Array filled with a specific value (shape & type)
filled_arr = np.full((3, 3), fill_value=7, dtype=int)
print("\n3. Full array (3x3 filled with 7):\n", filled_arr)

# 4. Zeros with same shape and type as another array
sample_arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
zeros_like_arr = np.zeros_like(sample_arr)
print("\n4. Zeros like existing array:\n", zeros_like_arr)

# 5. Ones with same shape and type as another array
ones_like_arr = np.ones_like(sample_arr)
print("\n5. Ones like existing array:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print("\n6. List converted to numpy array:\n", numpy_arr)


1. Empty array:
 [[4.4e-323 5.4e-323]
 [4.9e-323 5.9e-323]]

2. All-one array:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]

3. Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like existing array:
 [[0 0 0]
 [0 0 0]]

5. Ones like existing array:
 [[1 1 1]
 [1 1 1]]

6. List converted to numpy array:
 [1 2 3 4]


In [2]:
#Problem 2
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("1.\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2.\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3.\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4.\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5.\n", random_10x10)
print("Min:", min_value, "Max:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6.\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7.\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
n, m = 5, 5
border_array = np.ones((n, m))
border_array[1:-1, 1:-1] = 0
print("\n8.\n", border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", checkerboard)

1.
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4.
 [0.39007264 0.90798962 0.42785139 0.11914213 0.26577096 0.91019229
 0.09681521 0.64392636 0.68710444 0.40806207 0.90720033 0.3274531
 0.60080936 0.19717784 0.18148888 0.73965982 0.18744511 0.97103566
 0.65368161 0.31725767 0.25892296 0.98147442 0.38863081 0.92504245
 0.22481327 0.0388395  0.50528067 0.07226744 0.63009994 0.53195379]
Mean of the array: 0.4832487254142501

5.
 [[0.52140803 0.33459184 0.34565547 0.87887774 0.28065078 0.35807388
  0.96881962 0.00132214 0.34035908 0.85603153]
 [0.1287618  0.659442   0.61902947 0.37447272 0.298297   0.66978718
  0.36108633 0.24377867 0.06215424 0.54846621]
 [0.30391396 0.45529274 0.35629926 0.61757111 0.88503208 0.60904398
  0.34708347 0.32867064 0.55135089 0.87392312]
 [0.67927989 0.08974532 0.89556569 0.84282349 0.03972793 0.42048542
  

In [8]:
#Problem 3
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("1.(x + y):")
print(x + y)

print("\n2.(x - y):")
print(x - y)

print("\n3.(3 * x):")
print(3 * x)

print("\n4.(x**2):")
print(x**2)

print("\n5(a). Dot product of v.w:")
print(np.dot(v, w))

print("\n5(b). Dot product of x.v:")
print(np.dot(x, v))

print("\n5(c). Dot product of x .y:")
print(np.dot(x, y))

print("\n6(a). Concatenate x and y along rows:")
print(np.vstack((x, y)))

print("\n6(b). Concatenate v and w along columns:")
print(np.column_stack((v, w)))

print("\n7. Concatenate x and v (Shows error explanation):")
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("Error:", e)
    print("Reason: x is 2D but v is 1D. NumPy cannot concatenate arrays with different dimensions.")

1.(x + y):
[[ 6  8]
 [10 13]]

2.(x - y):
[[-4 -4]
 [-4 -3]]

3.(3 * x):
[[ 3  6]
 [ 9 15]]

4.(x**2):
[[ 1  4]
 [ 9 25]]

5(a). Dot product of v.w:
219

5(b). Dot product of x.v:
[29 77]

5(c). Dot product of x .y:
[[19 22]
 [50 58]]

6(a). Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

6(b). Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Concatenate x and v (Shows error explanation):
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D but v is 1D. NumPy cannot concatenate arrays with different dimensions.


In [6]:
#Problem 4
# Part 1: Matrices A and B

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 =\n", np.round(I, 2))

# Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("BA =\n", BA)

# Prove (AB)ᵀ = Bᵀ * Aᵀ
LHS = AB.T
RHS = np.dot(B.T, A.T)
print("\n\n(AB)^T =\n", LHS)
print("B^T * A^T =\n", RHS)


# Part 2: Solve linear system
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

# Method 1: Using inverse
X_inv = np.dot(np.linalg.inv(A_sys), B_sys)
print("\nSolution using inverse method [x, y, z] =", np.round(X_inv, 2))

# Method 2: Using np.linalg.solve (more efficient)
X_solve = np.linalg.solve(A_sys, B_sys)
print("Solution using np.linalg.solve [x, y, z] =", np.round(X_solve, 2))


A * A^-1 =
 [[1. 0.]
 [0. 1.]]

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]

Solution using inverse method [x, y, z] = [ 2.  1. -2.]
Solution using np.linalg.solve [x, y, z] = [ 2.  1. -2.]


In [9]:
# Experiment 4.2

import time
import numpy as np

print("1. ELEMENT-WISE ADDITION")

# Python list addition
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")

# NumPy addition
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")


print("\n2. ELEMENT-WISE MULTIPLICATION")

# Python list multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")

# NumPy multiplication
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")


print("\n3. DOT PRODUCT")

# Python list dot product
start = time.time()
dot_py = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")

# NumPy dot product
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start, "seconds")

print("\n4. MATRIX MULTIPLICATION (1000 x 1000)")

# Python list matrix multiplication
matrix1 = [[1]*1000 for _ in range(1000)]
matrix2 = [[1]*1000 for _ in range(1000)]

start = time.time()
result_matrix = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(1000))
    for j in range(1000)]
    for i in range(1000)
]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy matrix multiplication
np_matrix1 = np.ones((1000, 1000))
np_matrix2 = np.ones((1000, 1000))

start = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")


1. ELEMENT-WISE ADDITION
Python List Addition Time: 0.08348989486694336 seconds
NumPy Array Addition Time: 0.003195524215698242 seconds

2. ELEMENT-WISE MULTIPLICATION
Python List Multiplication Time: 0.07702350616455078 seconds
NumPy Array Multiplication Time: 0.0032205581665039062 seconds

3. DOT PRODUCT
Python List Dot Product Time: 0.06621146202087402 seconds
NumPy Dot Product Time: 0.0017018318176269531 seconds

4. MATRIX MULTIPLICATION (1000 x 1000)
Python List Matrix Multiplication Time: 76.37703776359558 seconds
NumPy Matrix Multiplication Time: 0.06145358085632324 seconds
